version: '3.1'

services:

  db:
    image: "mysql:5.7"
    command: --sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_PASSWORD: passme123
      MYSQL_DATABASE: gophish

  frontend:
    image: bullshit/gophish:latest
    environment:
      CONTACT_ADDRESS: "phising@example.tld"
      DB_DRIVER: mysql
      DB_USER: root
      DB_PASS: passme123
    depends_on:
      - db
    ports:
      - "80:80"
      - "3333:3333"
